### ISSUE TITLE
Update to match HA 0.96 climate cleanup

### ISSUE THREAD

**Issue by rest77** [djbulsink/panasonic_ac#6] opened 2019-07-18 05:28 UTC
The componenet needs to be updated to the HA 0.96 climate cleanup changes . Who has the time and knowledge to do so?

**Comment by SeraphimSerapis** [comment] 2019-07-18 05:48
I've started the work here: https://github.com/SeraphimSerapis/panasonic_ac (started with https://github.com/SeraphimSerapis/panasonic_ac/commit/2ddc529180b24c556ec3b6a9e6dfe54fa944f20e).

I'm currently on vacation and am not able to directly test my work. If anyone wants to help: feel free to commit changes according to https://github.com/home-assistant/home-assistant/pull/23899.

@djbulsink FYI

**Comment by rest77** [comment] 2019-07-18 06:27
I get the following error:

Log Details (ERROR)
Thu Jul 18 2019 08:26:08 GMT+0200 (Central European Summer Time)
Error executing service <ServiceCall homeassistant.restart (c:5bb9377d361b4ce3ab331ca678e84d4b)>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1159, in _safe_execute
    await self._execute_service(handler, service_call)
  File "/usr/src/homeassistant/homeassistant/core.py", line 1172, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/components/hassio/__init__.py", line 254, in async_handle_core_service
    errors = await conf_util.async_check_ha_config_file(hass)
  File "/usr/src/homeassistant/homeassistant/config.py", line 759, in async_check_ha_config_file
    res = await check_config.async_check_ha_config_file(hass)
  File "/usr/src/homeassistant/homeassistant/helpers/check_config.py", line 159, in async_check_ha_config_file
    platform = p_integration.get_platform(domain)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 220, in get_platform
    "{}.{}".format(self.pkg_path, platform_name)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/custom_components/panasonic_ac/climate.py", line 40, in <module>
    SUPPORT_OPERATION_MODE | SUPPORT_SWING_MODE |
NameError: name 'SUPPORT_OPERATION_MODE' is not defined

**Comment by SeraphimSerapis** [comment] 2019-07-18 06:34
Thanks for checking! My HA is currently not even starting on .96 (investigating remotely as well as I can), so I fear I won't be able to really push this forward much until I'm back in Germany (next week).

**Comment by SeraphimSerapis** [comment] 2019-07-19 05:10
@djbulsink it seems like you merged my commits into your codebase. Anything not working yet?

**Comment by olivierfaber** [comment] 2019-07-19 07:48
I'm not at home but it looks like its working. No errors in log :-)
Thanks guys!

![Panasonic](https://user-images.githubusercontent.com/25980325/61518624-4d9c6200-aa0a-11e9-8699-a6f03c756089.PNG)

**Comment by rest77** [comment] 2019-07-19 08:18
I tried as well without errors :-). But... turn off works fine. Turn on just sets automatic (instead of heat or cool) and does not turn on the device. How about the eco mode? Will say quiet or powerful if I read the docs (https://github.com/lostfields/python-panasonic-comfort-cloud) correct.

Good job everyone!

**Comment by djbulsink** [comment] 2019-07-25 19:57
I didn't had the time to look at this last couple of days, but thanks to the contribution of @SeraphimSerapis  the issue is fixed!

**Closed by djbulsink** 2019-07-25 19:57 UTC
